import Header from "@/components/Header/Header";
import Main from "@/components/Main/Main";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Cronos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Main />
      </main>
    </>
  );
}
